name: release
on:
  release:
    types:
      - created
env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  release_name: ${{ github.event.release.name }}

jobs:
  publish:
    name: publish ${{ matrix.os }} / ${{ matrix.architecture }} 🤖
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64]
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.10]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Set up Python 3 🐍
        uses: actions/setup-python@v4
        with:
          architecture: ${{ matrix.architecture }}
      - name: Update PIP ✨
        if: ${{ matrix.os }} != windows-latest
        run: python3 -m pip install -U wheel pip setuptools
      - name: Install requirements
        run: pip install -r requirements.txt PyGithub
      - name: Build and Publish 📦
        run: |
          python3 .github/workflows/publish.py
