name: test
on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "examples/**"
      - ".github/workflows/test.yaml"
      - "Makefile"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "examples/**"
      - ".github/workflows/test.yaml"
      - "Makefile"
jobs:
  test:
    name: Run Tests 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Set up Python 3 🐍
        uses: actions/setup-python@v4
        with:
          architecture: x64
      - name: Update PIP ✨
        run: pip install -U wheel pip setuptools
      - name: Install requirements ⚙️
        run: |
          pip install -r requirements.txt pytest
      - name: build 🏗️
        run: |
          make build
      - name: Test 🧪
        run: |
          make tests
